
import Register.regiterform;
import com.mysql.jdbc.Connection;
import home.home;
import java.awt.HeadlessException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dasun
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        forgotpssbtn.setOpaque(false);
        forgotpssbtn.setContentAreaFilled(false);
        forgotpssbtn.setBorderPainted(false);
        
        signupbtn.setOpaque(false);
        signupbtn.setContentAreaFilled(false);
        signupbtn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        logginbtn = new javax.swing.JButton();
        checkbox = new javax.swing.JCheckBox();
        forgotpssbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        signupbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText(" Log in to System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 210, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 60)); // NOI18N
        jLabel2.setText("Learning Mangement System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("  Student ID : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        studentid.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentidFocusGained(evt);
            }
        });
        studentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentidActionPerformed(evt);
            }
        });
        jPanel1.add(studentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 410, 42));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("  Password :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 410, 42));

        logginbtn.setBackground(new java.awt.Color(51, 153, 255));
        logginbtn.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        logginbtn.setForeground(new java.awt.Color(255, 255, 255));
        logginbtn.setText("login");
        logginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logginbtnActionPerformed(evt);
            }
        });
        jPanel1.add(logginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 160, 60));

        checkbox.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        checkbox.setText("Show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        jPanel1.add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 210, -1));

        forgotpssbtn.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        forgotpssbtn.setForeground(new java.awt.Color(102, 102, 102));
        forgotpssbtn.setText("Forgot your password ?");
        forgotpssbtn.setBorder(null);
        forgotpssbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotpssbtnActionPerformed(evt);
            }
        });
        jPanel1.add(forgotpssbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, -1, 50));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 948, -1, -1));

        signupbtn.setBackground(new java.awt.Color(255, 255, 255));
        signupbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        signupbtn.setText("Don't have an account?  Signup here");
        signupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupbtnActionPerformed(evt);
            }
        });
        jPanel1.add(signupbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 370, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/2147655814.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 1000));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        if(checkbox.isSelected()){
            password.setEchoChar((char)0);
            checkbox.setText("Hide password");
        }
        
        else {
            password.setEchoChar(('*'));
            checkbox.setText("Show password");
        }
    }//GEN-LAST:event_checkboxActionPerformed

    private void forgotpssbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotpssbtnActionPerformed
        
    }//GEN-LAST:event_forgotpssbtnActionPerformed

    private void logginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logginbtnActionPerformed
        String user,pass;
        user=studentid.getText();
        pass=password.getText(); 
        
         
        
            ResultSet rs = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/lms", "root", "");
             PreparedStatement ps = conn.prepareStatement("SELECT * FROM register WHERE Student_ID=? AND passwords=?");
            
            ps.setString(1, user);
            ps.setString(2, pass);
            
            rs = ps.executeQuery();
            if (rs.next())
        {
            setVisible(false);
            home object = new home();
            object.setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Invalid Login! ");
        }
             
        } catch (HeadlessException | ClassNotFoundException | SQLException e){
            
            
        }
        
        
        
        
    }//GEN-LAST:event_logginbtnActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void studentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidActionPerformed

    private void signupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnActionPerformed
        new regiterform().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupbtnActionPerformed

    private void studentidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentidFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_studentidFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NewJFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JButton forgotpssbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logginbtn;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signupbtn;
    private javax.swing.JTextField studentid;
    // End of variables declaration//GEN-END:variables
}
